### ISSUE TITLE
Is the bevy_lunex crate using the specified version

### ISSUE THREAD

**Issue by kyrosle** [IDEDARY/Bevypunk#21]
Here in the Cargo.toml file, the bevy_lunex is specified as computer loacal path, when i using the newest bevy_lunex the project throw out the error: 
```
no function or associated item named `new` found for struct `lunex_engine::nodes::structs::NodeTree` in the current scope
items from traits can only be used if the trait is in scoperustc[Click for full compiler diagnostic](rust-analyzer-diagnostics-view:/diagnostic%20message%20%5B5%5D?5#file%3A%2F%2F%2FUsers%2Fkyros%2FWorkStation%2Frust%2FBevypunk%2Fsrc%2Froutes%2Fgame%2Froute.rs)
```
```toml
  # UI framework
  # bevy_lunex = "0.2.1"
  bevy_lunex = { git = "https://github.com/bytestring-net/bevy_lunex", branch="dev", features=["kira"] }
  # bevy_lunex = { path = "/home/dominik/Projects/Bytestring/bevy_lunex/crates/bevy_lunex", features=["kira"] }
```

**Comment by IDEDARY** [comment]
This repository is being used to dogfeed the Bevy Lunex library. The project is setup in a way to allow me to quickly iterate and see changes right when I made them, thus the local crate path. If you need to compile, you have to change the version with the commented out one.

The reason why the bleeding edge version didnt work, was because bevy_lunex "dev" branch is synced up with bevypunk "dev" branch and thus ahead of bevypunk "main".

Anyway, I have synced these branches now, it should work :)
